server:
  port: 8081

spring:
  application:
    name: USERSSERVICE
  config:
    import: optional:configserver:http://localhost:8084

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#eureka:
#  client:
#    instance:
#      preferIpAddress: true
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreaker:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      RatingHotelBreaker :
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindow: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      RatingHotelService:
        maxAttempts: 3
        waitDuration: 5s

  ratelimiter:
    instances:
      UserRateLimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 0s
